server:
  port: 9095
spring:
  application:
    name: book-management-service
  datasource:
    url: jdbc:mysql://localhost:3306/online_book_store
    username: sipun
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:9090/eureka}